### PR TITLE
Use relative path for /assets

### LINKED ISSUE #2: OSError: Read-Only file system: '/assets'
Running the script on a mac, i get an error trying to write to `/assets`. This is coming from line `:105`, and works if i change it to a relative path instead of the root directory.  See pull request for my fix.

### PR DESCRIPTION
**Pull request by joe-toolhouse**
Fixes https://github.com/seanthegeek/wp2jekyll/issues/2

### CODE REVIEW

**Review by stfnjstn — COMMENTED** [review]
I came to the same solution, trying to get it running on a mac

**Comment by seanthegeek** [comment]
This PR would fix the filesystem issue but would cause invalid URIs to be written. I think I came up with a better solution. Try the version that I just committed to the repository.

**Comment by seanthegeek** [comment]
@stfnjstn Does your thumbs up reaction mean that worked?

**Comment by stfnjstn** [comment]
Yes, it worked

**Pull request closed without merging**
